refactor: backend

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -3,6 +3,6 @@
 echo "Linting"
 golangci-lint run
 if [ $? -ne 0 ]; then
-    echo "golangci-lint failed. Please fix the errors before committing."
-    exit 1
+  echo "golangci-lint failed."
+  exit 1
 fi
